/*
 Esta clase tem de interagir com o usuario na incerçao de uma nova Turma no sistema da Escola, 
 executa a funcionalidade de cada botao gerando o caminho e os dados para serem enviados ao banco de dados.
 */
package visao;

import java.sql.SQLException;
import modeloConection.ConexaoBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansTurma;
import modeloBeans.ModeloTabela;
import modeloDao.DaoTurma;

/**
 *
 * @author Ivan
 */
public class FormTurma extends javax.swing.JFrame {

    BeansTurma mod = new BeansTurma();
    DaoTurma control = new DaoTurma();
    ConexaoBD conex = new ConexaoBD();
    int key = 0;
    
    public FormTurma(){
        initComponents();
        preencherTablela("select * from turma order by DESCRI_TUR;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanelFormProfessor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeTurma = new javax.swing.JTextField();
        jButtonNovoTurma = new javax.swing.JButton();
        jButtonSalvarTurma = new javax.swing.JButton();
        jButtonEditarTurma = new javax.swing.JButton();
        jButtonCancelarTurma = new javax.swing.JButton();
        jButtonExcluirTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurma = new javax.swing.JTable();
        jTextFieldPesquisaTurma = new javax.swing.JTextField();
        jButtonPesquisaTurma = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoTurma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFormProfessor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelFormProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descricao:");

        jTextFieldNomeTurma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNomeTurma.setEnabled(false);
        jTextFieldNomeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeTurmaActionPerformed(evt);
            }
        });

        jButtonNovoTurma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovoTurma.setText("Novo");
        jButtonNovoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoTurmaActionPerformed(evt);
            }
        });

        jButtonSalvarTurma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSalvarTurma.setText("Salvar");
        jButtonSalvarTurma.setEnabled(false);
        jButtonSalvarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTurmaActionPerformed(evt);
            }
        });

        jButtonEditarTurma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditarTurma.setText("Editar");
        jButtonEditarTurma.setEnabled(false);
        jButtonEditarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarTurmaActionPerformed(evt);
            }
        });

        jButtonCancelarTurma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelarTurma.setText("Cancelar");
        jButtonCancelarTurma.setEnabled(false);
        jButtonCancelarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarTurmaActionPerformed(evt);
            }
        });

        jButtonExcluirTurma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonExcluirTurma.setText("Excluir");
        jButtonExcluirTurma.setEnabled(false);
        jButtonExcluirTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTurmaActionPerformed(evt);
            }
        });

        jTableTurma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTurmaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTurma);

        jTextFieldPesquisaTurma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldPesquisaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaTurmaActionPerformed(evt);
            }
        });

        jButtonPesquisaTurma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisaTurma.setText("Pesquisar");
        jButtonPesquisaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaTurmaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Codigo:");

        jTextFieldCodigoTurma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCodigoTurma.setEnabled(false);
        jTextFieldCodigoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormProfessorLayout = new javax.swing.GroupLayout(jPanelFormProfessor);
        jPanelFormProfessor.setLayout(jPanelFormProfessorLayout);
        jPanelFormProfessorLayout.setHorizontalGroup(
            jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelarTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormProfessorLayout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisaTurma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisaTurma)))
                        .addGap(34, 34, 34))))
        );
        jPanelFormProfessorLayout.setVerticalGroup(
            jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCodigoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisaTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jButtonNovoTurma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarTurma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarTurma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarTurma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirTurma)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Turma:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFormProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(671, 671, 671))
        );

        setSize(new java.awt.Dimension(687, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeTurmaActionPerformed

    
    private void jButtonSalvarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarTurmaActionPerformed
        if (jTextFieldCodigoTurma.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CODIGO para continuar");
            jTextFieldCodigoTurma.requestFocus();
        }else if (jTextFieldNomeTurma.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Informe a DESCRICAO da Turma");
            jTextFieldNomeTurma.requestFocus();
        }else 
 
        if (key == 1) {
           mod.setTur_cod(jTextFieldCodigoTurma.getText());
           mod.setTur_nome(jTextFieldNomeTurma.getText());
           control.Salvar(mod);
           
           jTextFieldCodigoTurma.setText("");
           jTextFieldNomeTurma.setText("");
           
           jTextFieldCodigoTurma.setEnabled(false);
           jTextFieldNomeTurma.setEnabled(false);

           
           jButtonSalvarTurma.setEnabled(false);
           jButtonCancelarTurma.setEnabled(false);
           jButtonPesquisaTurma.setEnabled(true);
           jTextFieldPesquisaTurma.setText("");
           jTextFieldPesquisaTurma.setEnabled(true);
           key = 0;
           preencherTablela("select * from turma order by DESCRI_TUR;");
       }
          
       if (key == 2){
           mod.setTur_cod(jTextFieldCodigoTurma.getText());
           mod.setTur_nome(jTextFieldNomeTurma.getText());
           control.Editar(mod);
           
           jTextFieldCodigoTurma.setText("");
           jTextFieldNomeTurma.setText("");
           
           jTextFieldCodigoTurma.setEnabled(false);
           jTextFieldNomeTurma.setEnabled(false);
          
           jButtonNovoTurma.setEnabled(true);
           jButtonCancelarTurma.setEnabled(false);
           
           key = 0;
           preencherTablela("select * from turma order by DESCRI_TUR;");
       }
       
    }//GEN-LAST:event_jButtonSalvarTurmaActionPerformed

    private void jButtonNovoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoTurmaActionPerformed
        key = 1;
        jTextFieldCodigoTurma.setText("");
        jTextFieldNomeTurma.setText("");

        jTextFieldPesquisaTurma.setEnabled(false);
        jTextFieldCodigoTurma.setEnabled(true);
        jTextFieldNomeTurma.setEnabled(true);

        jButtonSalvarTurma.setEnabled(true);
        jButtonEditarTurma.setEnabled(false);
        jButtonExcluirTurma.setEnabled(false);
        jButtonPesquisaTurma.setEnabled(false);
        jButtonCancelarTurma.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoTurmaActionPerformed

    private void jButtonCancelarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarTurmaActionPerformed
        jTextFieldCodigoTurma.setText("");
        jTextFieldNomeTurma.setText("");
        
        jTextFieldPesquisaTurma.setEnabled(true);
        jTextFieldNomeTurma.setEnabled(false);
        jTextFieldCodigoTurma.setEnabled(false);
        
        jButtonPesquisaTurma.setEnabled(true);
        jButtonSalvarTurma.setEnabled(false);
        jButtonCancelarTurma.setEnabled(false);
        jButtonNovoTurma.setEnabled(true);
        jButtonEditarTurma.setEnabled(false);
        jButtonExcluirTurma.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarTurmaActionPerformed

    private void jButtonEditarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarTurmaActionPerformed
        key = 2;
        jTextFieldNomeTurma.setEnabled(true);
        jTextFieldCodigoTurma.setEnabled(false);
        
        jButtonSalvarTurma.setEnabled(true);
        jButtonCancelarTurma.setEnabled(true);
        jButtonEditarTurma.setEnabled(false);
        jButtonNovoTurma.setEnabled(false);
        jButtonExcluirTurma.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarTurmaActionPerformed

    private void jTextFieldCodigoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoTurmaActionPerformed

    private void jButtonExcluirTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTurmaActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setTur_cod(jTextFieldCodigoTurma.getText());
            control.Excluir(mod);
            jTextFieldNomeTurma.setText("");
            jTextFieldCodigoTurma.setText("");
            jTextFieldPesquisaTurma.setText("");
            
            jTextFieldNomeTurma.setEnabled(false);
            jTextFieldCodigoTurma.setEnabled(false);
            jTextFieldPesquisaTurma.setEnabled(true);
            
            jButtonSalvarTurma.setEnabled(false);
            jButtonEditarTurma.setEnabled(false);
            jButtonExcluirTurma.setEnabled(false);
            jButtonCancelarTurma.setEnabled(false);
            preencherTablela("select * from turma order by DESCRI_TUR;");
        }
    }//GEN-LAST:event_jButtonExcluirTurmaActionPerformed

    private void jTableTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTurmaMouseClicked
        String nome_turma = ""+jTableTurma.getValueAt(jTableTurma.getSelectedRow(), 1);
        conex.conecxao();
        conex.executaSql("select * from turma where DESCRI_TUR = '" + nome_turma + "';");
        try {
            conex.rs.first();
            jTextFieldCodigoTurma.setText(String.valueOf(conex.rs.getString("COD_TUR")));
            jTextFieldNomeTurma.setText(conex.rs.getString("DESCRI_TUR"));
            
            jButtonEditarTurma.setEnabled(true);
            jButtonExcluirTurma.setEnabled(true);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados!" + ex);
        }
        
        conex.desconectar();
    }//GEN-LAST:event_jTableTurmaMouseClicked

    private void jTextFieldPesquisaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaTurmaActionPerformed

    private void jButtonPesquisaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaTurmaActionPerformed
        mod.setTur_pesquisa(jTextFieldPesquisaTurma.getText());
        BeansTurma model = control.buscaBeansTurma(mod);
        jTextFieldNomeTurma.setText(model.getTur_nome());
        jTextFieldCodigoTurma.setText(String.valueOf(model.getTur_cod()));

        preencherTablela("select*from turma where DESCRI_TUR like'%"+mod.getTur_pesquisa()+"%'");

    }//GEN-LAST:event_jButtonPesquisaTurmaActionPerformed

   public void preencherTablela(String Sql) {
       ArrayList dados = new ArrayList();
       String [] colunas = new String [] {"ID","Descri. Turma"};
       conex.conecxao();
       
       conex.executaSql(Sql);
       
       try{
           conex.rs.first();
           do {
               dados.add(new Object[]{conex.rs.getString("COD_TUR"),conex.rs.getString("DESCRI_TUR")});  
           }while(conex.rs.next());
           
       }catch(SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Nenhum resultado encontrado na tabela.");
       }
       ModeloTabela modelo = new ModeloTabela(dados, colunas);
       
       jTableTurma.setModel(modelo);
       jTableTurma.getColumnModel().getColumn(0).setPreferredWidth(90);
       jTableTurma.getColumnModel().getColumn(0).setResizable(false);
       jTableTurma.getColumnModel().getColumn(1).setPreferredWidth(100);
       jTableTurma.getColumnModel().getColumn(1).setResizable(false);
       jTableTurma.getTableHeader().setReorderingAllowed(false);
       jTableTurma.setAutoResizeMode(jTableTurma.AUTO_RESIZE_OFF);
       jTableTurma.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
       conex.desconectar();
   } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new FormTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarTurma;
    private javax.swing.JButton jButtonEditarTurma;
    private javax.swing.JButton jButtonExcluirTurma;
    private javax.swing.JButton jButtonNovoTurma;
    private javax.swing.JButton jButtonPesquisaTurma;
    private javax.swing.JButton jButtonSalvarTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelFormProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTurma;
    private javax.swing.JTextField jTextFieldCodigoTurma;
    private javax.swing.JTextField jTextFieldNomeTurma;
    private javax.swing.JTextField jTextFieldPesquisaTurma;
    // End of variables declaration//GEN-END:variables
}
