/*
 Esta clase tem de interagir com o usuario na incerçao de um novo Professor no sistema da Escola, 
 executa a funcionalidade de cada botao gerando o caminho e os dados para serem enviados ao banco de dados.
 */
package visao;

import java.sql.SQLException;
import modeloConection.ConexaoBD;
import modeloDao.DaoProf;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansProfessor;
import modeloBeans.ModeloTabela;

/**
 *
 * @author Ivan
 */
public class FormProfessor extends javax.swing.JFrame {

    BeansProfessor mod = new BeansProfessor();
    DaoProf control = new DaoProf();
    ConexaoBD conex = new ConexaoBD();
    int key = 0;
    
    public FormProfessor(){
        initComponents();
        preencherTablela("select * from professor order by NOME_PROF;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormProfessor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeProf = new javax.swing.JTextField();
        jTextFieldFormacaoProf = new javax.swing.JTextField();
        jComboBoxTipoFormacaoProf = new javax.swing.JComboBox<>();
        jButtonNovoProf = new javax.swing.JButton();
        jButtonSalvarProf = new javax.swing.JButton();
        jButtonEditarProf = new javax.swing.JButton();
        jButtonCancelarProf = new javax.swing.JButton();
        jButtonExcluirProf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfessor = new javax.swing.JTable();
        jTextFieldPesquisaProf = new javax.swing.JTextField();
        jButtonPesquisaProf = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoProf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldCelularProf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFoneProf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFormProfessor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelFormProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Formação:");

        jTextFieldNomeProf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNomeProf.setEnabled(false);
        jTextFieldNomeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProfActionPerformed(evt);
            }
        });

        jTextFieldFormacaoProf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldFormacaoProf.setEnabled(false);
        jTextFieldFormacaoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormacaoProfActionPerformed(evt);
            }
        });

        jComboBoxTipoFormacaoProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxTipoFormacaoProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superior", "Baixarel", "Mestrado", "Doutorado" }));
        jComboBoxTipoFormacaoProf.setEnabled(false);
        jComboBoxTipoFormacaoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoFormacaoProfActionPerformed(evt);
            }
        });

        jButtonNovoProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovoProf.setText("Novo");
        jButtonNovoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoProfActionPerformed(evt);
            }
        });

        jButtonSalvarProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSalvarProf.setText("Salvar");
        jButtonSalvarProf.setEnabled(false);
        jButtonSalvarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProfActionPerformed(evt);
            }
        });

        jButtonEditarProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditarProf.setText("Editar");
        jButtonEditarProf.setEnabled(false);
        jButtonEditarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProfActionPerformed(evt);
            }
        });

        jButtonCancelarProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelarProf.setText("Cancelar");
        jButtonCancelarProf.setEnabled(false);
        jButtonCancelarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProfActionPerformed(evt);
            }
        });

        jButtonExcluirProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonExcluirProf.setText("Excluir");
        jButtonExcluirProf.setEnabled(false);
        jButtonExcluirProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProfActionPerformed(evt);
            }
        });

        jTableProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProfessorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProfessor);

        jTextFieldPesquisaProf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonPesquisaProf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisaProf.setText("Pesquisar");
        jButtonPesquisaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaProfActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Codigo:");

        jTextFieldCodigoProf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCodigoProf.setEnabled(false);
        jTextFieldCodigoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Telefone:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Celular:");

        try {
            jFormattedTextFieldCelularProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelularProf.setText("(**) * ****-****");
        jFormattedTextFieldCelularProf.setEnabled(false);
        jFormattedTextFieldCelularProf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        try {
            jFormattedTextFieldFoneProf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFoneProf.setText("(**) * ****-****");
        jFormattedTextFieldFoneProf.setEnabled(false);
        jFormattedTextFieldFoneProf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jFormattedTextFieldFoneProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFoneProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormProfessorLayout = new javax.swing.GroupLayout(jPanelFormProfessor);
        jPanelFormProfessor.setLayout(jPanelFormProfessorLayout);
        jPanelFormProfessorLayout.setHorizontalGroup(
            jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelarProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisaProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaProf))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeProf))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFormacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jComboBoxTipoFormacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldFoneProf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCelularProf)
                        .addGap(70, 70, 70)))
                .addGap(34, 34, 34))
        );
        jPanelFormProfessorLayout.setVerticalGroup(
            jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCodigoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldFormacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoFormacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextFieldCelularProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldFoneProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jButtonNovoProf)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarProf)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarProf)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarProf)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirProf)))
                .addGap(17, 17, 17)
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Professor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFormProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFormProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );

        setSize(new java.awt.Dimension(687, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProfActionPerformed

    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    java.sql.Date nascProf;
   
    
    private void jButtonSalvarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProfActionPerformed
        if (jTextFieldNomeProf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o NOME para continuar");
            jTextFieldNomeProf.requestFocus();
        }else if (jTextFieldFormacaoProf.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Informe a FORMAÇAO para continuar");
            jTextFieldNomeProf.requestFocus();
        }else if (jFormattedTextFieldCelularProf.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Informe o CELULAR para continuar");
            jTextFieldNomeProf.requestFocus();
        } else
        if (key == 1) {
           mod.setProf_nome(jTextFieldNomeProf.getText());
           mod.setProf_form(jTextFieldFormacaoProf.getText());
           mod.setTipo_form((String) jComboBoxTipoFormacaoProf.getSelectedItem());
           mod.setProf_cel(jFormattedTextFieldCelularProf.getText());
           mod.setProf_tel(jFormattedTextFieldFoneProf.getText());
           control.Salvar(mod);
           jTextFieldNomeProf.setText("");
           jTextFieldFormacaoProf.setText("");
           jFormattedTextFieldCelularProf.setText("");
           jFormattedTextFieldFoneProf.setText("");
           jTextFieldNomeProf.setEnabled(false);
           jTextFieldFormacaoProf.setEnabled(false);
           jComboBoxTipoFormacaoProf.setEnabled(false);
           jFormattedTextFieldCelularProf.setEnabled(false);
           jFormattedTextFieldFoneProf.setEnabled(false);
           jButtonSalvarProf.setEnabled(false);
           jButtonCancelarProf.setEnabled(false);
           jButtonPesquisaProf.setEnabled(true);
           jTextFieldPesquisaProf.setText("");
           jTextFieldPesquisaProf.setEnabled(true);
           key = 0;
           preencherTablela("select * from professor order by NOME_PROF;");
       } else
          
       if (key == 2){
           mod.setProf_cod(Integer.parseInt(jTextFieldCodigoProf.getText()));
           mod.setProf_nome(jTextFieldNomeProf.getText());
           mod.setProf_form(jTextFieldFormacaoProf.getText());
           mod.setTipo_form((String) jComboBoxTipoFormacaoProf.getSelectedItem());
           mod.setProf_cel(jFormattedTextFieldCelularProf.getText());
           mod.setProf_tel(jFormattedTextFieldFoneProf.getText());
           control.Editar(mod);
           jTextFieldNomeProf.setText("");
           jTextFieldFormacaoProf.setText("");
           jFormattedTextFieldCelularProf.setText("");
           jFormattedTextFieldFoneProf.setText("");
           jTextFieldCodigoProf.setText("");
           jTextFieldNomeProf.setEnabled(false);
           jTextFieldFormacaoProf.setEnabled(false);
           jComboBoxTipoFormacaoProf.setEnabled(false);
           jFormattedTextFieldCelularProf.setEnabled(false);
           jFormattedTextFieldFoneProf.setEnabled(false);
           jButtonNovoProf.setEnabled(true);
           jButtonCancelarProf.setEnabled(false);
           key = 0;
           preencherTablela("select * from professor order by NOME_PROF;");
       }
       
    }//GEN-LAST:event_jButtonSalvarProfActionPerformed

    private void jButtonNovoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoProfActionPerformed
        key = 1;
        jTextFieldNomeProf.setText("");
        jTextFieldFormacaoProf.setText("");
        jFormattedTextFieldCelularProf.setText("");
        jFormattedTextFieldFoneProf.setText("");
        jTextFieldCodigoProf.setText("");
        jTextFieldPesquisaProf.setText("");
        jTextFieldPesquisaProf.setEnabled(false);
        jTextFieldNomeProf.setEnabled(true);
        jTextFieldFormacaoProf.setEnabled(true);
        jComboBoxTipoFormacaoProf.setEnabled(true);
        jFormattedTextFieldCelularProf.setEnabled(true);
        jFormattedTextFieldFoneProf.setEnabled(true);
        jButtonSalvarProf.setEnabled(true);
        jButtonEditarProf.setEnabled(false);
        jButtonExcluirProf.setEnabled(false);
        jButtonPesquisaProf.setEnabled(false);
        jButtonCancelarProf.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoProfActionPerformed

    private void jComboBoxTipoFormacaoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoFormacaoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoFormacaoProfActionPerformed

    private void jTextFieldFormacaoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormacaoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormacaoProfActionPerformed

    private void jButtonPesquisaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaProfActionPerformed
        mod.setProf_pesquisa(jTextFieldPesquisaProf.getText());
        BeansProfessor model = control.buscaBeansProfessor(mod);
        jTextFieldNomeProf.setText(model.getProf_nome());
        jTextFieldCodigoProf.setText(String.valueOf(model.getProf_cod()));
        jTextFieldFormacaoProf.setText(model.getProf_form());
        jComboBoxTipoFormacaoProf.setSelectedItem(model.getTipo_form());
        jFormattedTextFieldCelularProf.setText(model.getProf_cel());
        jFormattedTextFieldFoneProf.setText(model.getProf_tel());
        preencherTablela("select*from professor where NOME_PROF like'%"+mod.getProf_pesquisa()+"%'");
       
    }//GEN-LAST:event_jButtonPesquisaProfActionPerformed

    private void jButtonCancelarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProfActionPerformed
        jTextFieldNomeProf.setText("");
        jTextFieldFormacaoProf.setText("");
        jFormattedTextFieldCelularProf.setText("");
        jFormattedTextFieldFoneProf.setText("");
        jTextFieldCodigoProf.setText("");
        jTextFieldPesquisaProf.setText("");
        jTextFieldPesquisaProf.setEnabled(true);
        jTextFieldNomeProf.setEnabled(false);
        jTextFieldFormacaoProf.setEnabled(false);
        jComboBoxTipoFormacaoProf.setEnabled(false);
        jFormattedTextFieldCelularProf.setEnabled(false);
        jFormattedTextFieldFoneProf.setEnabled(false);
        jButtonPesquisaProf.setEnabled(true);
        jButtonSalvarProf.setEnabled(false);
        jButtonCancelarProf.setEnabled(false);
        jButtonNovoProf.setEnabled(true);
        jButtonEditarProf.setEnabled(false);
        jButtonExcluirProf.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarProfActionPerformed

    private void jButtonEditarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProfActionPerformed
        key = 2;
        jTextFieldNomeProf.setEnabled(true);
        jTextFieldFormacaoProf.setEnabled(true);
        jComboBoxTipoFormacaoProf.setEnabled(true);           
        jFormattedTextFieldCelularProf.setEnabled(true);
        jFormattedTextFieldFoneProf.setEnabled(true);
        jButtonSalvarProf.setEnabled(true);
        jButtonCancelarProf.setEnabled(true);
        jButtonEditarProf.setEnabled(false);
        jButtonNovoProf.setEnabled(false);
        jButtonExcluirProf.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarProfActionPerformed

    private void jTextFieldCodigoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProfActionPerformed

    private void jFormattedTextFieldFoneProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFoneProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFoneProfActionPerformed

    private void jButtonExcluirProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProfActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setProf_cod(Integer.parseInt(jTextFieldCodigoProf.getText()));
            control.Excluir(mod);
            jTextFieldNomeProf.setText("");
            jTextFieldFormacaoProf.setText("");
            jFormattedTextFieldCelularProf.setText("");
            jFormattedTextFieldFoneProf.setText("");
            jTextFieldCodigoProf.setText("");
            jTextFieldPesquisaProf.setText("");
            jTextFieldNomeProf.setEnabled(false);
            jTextFieldFormacaoProf.setEnabled(false);
            jComboBoxTipoFormacaoProf.setEnabled(false);
            jFormattedTextFieldCelularProf.setEnabled(false);
            jFormattedTextFieldFoneProf.setEnabled(false);
            jButtonSalvarProf.setEnabled(false);
            jButtonEditarProf.setEnabled(false);
            jButtonExcluirProf.setEnabled(false);
            jButtonCancelarProf.setEnabled(false);
            preencherTablela("select * from professor order by NOME_PROF;");
        }
    }//GEN-LAST:event_jButtonExcluirProfActionPerformed

    private void jTableProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProfessorMouseClicked
        String nome_professor = ""+jTableProfessor.getValueAt(jTableProfessor.getSelectedRow(), 1);
        conex.conecxao();
        conex.executaSql("select * from professor where NOME_PROF = '" + nome_professor + "';");
        try {
            conex.rs.first();
            jTextFieldCodigoProf.setText(String.valueOf(conex.rs.getString("COD_PROF")));
            jTextFieldNomeProf.setText(conex.rs.getString("NOME_PROF"));
            jTextFieldFormacaoProf.setText(conex.rs.getString("FORMA_PROF"));
            jComboBoxTipoFormacaoProf.setSelectedItem(conex.rs.getString("TIPO_FORM"));
            jFormattedTextFieldFoneProf.setText(conex.rs.getString("FONE_PROF")); 
            jFormattedTextFieldCelularProf.setText(conex.rs.getString("CEL_PROF"));
            jButtonEditarProf.setEnabled(true);
            jButtonExcluirProf.setEnabled(true);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados!" + ex);
        }
        
        conex.desconectar();
    }//GEN-LAST:event_jTableProfessorMouseClicked

   public void preencherTablela(String Sql) {
       ArrayList dados = new ArrayList();
       String [] colunas = new String [] {"ID","Nome","Formacão","Tipo","Telefone","Celular"};
       conex.conecxao();
       
       conex.executaSql(Sql);
       
       try{
           conex.rs.first();
           do {
               dados.add(new Object[]{conex.rs.getInt("COD_PROF"),conex.rs.getString("NOME_PROF"),conex.rs.getString("FORMA_PROF"),conex.rs.getString("TIPO_FORM"),conex.rs.getString("FONE_PROF"),conex.rs.getString("CEL_PROF")});  
           }while(conex.rs.next());
           
       }catch(SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Nenhum resultado encontrado na tabela.");
       }
       ModeloTabela modelo = new ModeloTabela(dados, colunas);
       
       jTableProfessor.setModel(modelo);
       jTableProfessor.getColumnModel().getColumn(0).setPreferredWidth(30);
       jTableProfessor.getColumnModel().getColumn(0).setResizable(false);
       jTableProfessor.getColumnModel().getColumn(1).setPreferredWidth(150);
       jTableProfessor.getColumnModel().getColumn(1).setResizable(false);
       jTableProfessor.getColumnModel().getColumn(2).setPreferredWidth(150);
       jTableProfessor.getColumnModel().getColumn(2).setResizable(false);
       jTableProfessor.getColumnModel().getColumn(3).setPreferredWidth(150);
       jTableProfessor.getColumnModel().getColumn(3).setResizable(false);
       jTableProfessor.getColumnModel().getColumn(4).setPreferredWidth(100);
       jTableProfessor.getColumnModel().getColumn(4).setResizable(false);
       jTableProfessor.getColumnModel().getColumn(5).setPreferredWidth(100);
       jTableProfessor.getColumnModel().getColumn(5).setResizable(false);
       jTableProfessor.getTableHeader().setReorderingAllowed(false);
       jTableProfessor.setAutoResizeMode(jTableProfessor.AUTO_RESIZE_OFF);
       jTableProfessor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
       conex.desconectar();
   } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new FormProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarProf;
    private javax.swing.JButton jButtonEditarProf;
    private javax.swing.JButton jButtonExcluirProf;
    private javax.swing.JButton jButtonNovoProf;
    private javax.swing.JButton jButtonPesquisaProf;
    private javax.swing.JButton jButtonSalvarProf;
    private javax.swing.JComboBox<String> jComboBoxTipoFormacaoProf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularProf;
    private javax.swing.JFormattedTextField jFormattedTextFieldFoneProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelFormProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfessor;
    private javax.swing.JTextField jTextFieldCodigoProf;
    private javax.swing.JTextField jTextFieldFormacaoProf;
    private javax.swing.JTextField jTextFieldNomeProf;
    private javax.swing.JTextField jTextFieldPesquisaProf;
    // End of variables declaration//GEN-END:variables
}
