/*
 Esta clase tem de interagir com o usuario na incerçao de um novo Aluno no sistema da Escola, 
 executa a funcionalidade de cada botao gerando o caminho e os dados para serem enviados ao banco de dados.
 */

package visao;

import modeloDao.DaoAluno;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import javax.swing.JOptionPane;
import modeloBeans.BeansAluno;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Ivan
 */
public class FormAluno extends javax.swing.JFrame {

    BeansAluno mod = new BeansAluno();
    DaoAluno control = new DaoAluno();
    ConexaoBD conex = new ConexaoBD();
    int key = 0;
    String data_banco;
    Date data_inicial;
    
    public FormAluno(){
        initComponents();
        preencherTablela("select * from aluno order by NOME_ALU;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanelFormProfessor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeAlu = new javax.swing.JTextField();
        jTextFieldMaeAlu = new javax.swing.JTextField();
        jButtonNovoAlu = new javax.swing.JButton();
        jButtonSalvarAluno = new javax.swing.JButton();
        jButtonEditarAluno = new javax.swing.JButton();
        jButtonCancelarAluno = new javax.swing.JButton();
        jButtonExcluirAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jTextFieldPesquisaAluno = new javax.swing.JTextField();
        jButtonPesquisaAluno = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoAlu = new javax.swing.JTextField();
        jTextFieldPaiAlu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldFoneAlu = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldNascAlu = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelularAlu = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFormProfessor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelFormProfessor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Mãe:");

        jTextFieldNomeAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldNomeAlu.setEnabled(false);
        jTextFieldNomeAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeAluActionPerformed(evt);
            }
        });

        jTextFieldMaeAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldMaeAlu.setEnabled(false);
        jTextFieldMaeAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaeAluActionPerformed(evt);
            }
        });

        jButtonNovoAlu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonNovoAlu.setText("Novo");
        jButtonNovoAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoAluActionPerformed(evt);
            }
        });

        jButtonSalvarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSalvarAluno.setText("Salvar");
        jButtonSalvarAluno.setEnabled(false);
        jButtonSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlunoActionPerformed(evt);
            }
        });

        jButtonEditarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditarAluno.setText("Editar");
        jButtonEditarAluno.setEnabled(false);
        jButtonEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAlunoActionPerformed(evt);
            }
        });

        jButtonCancelarAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelarAluno.setText("Cancelar");
        jButtonCancelarAluno.setEnabled(false);
        jButtonCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlunoActionPerformed(evt);
            }
        });

        jButtonExcluirAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonExcluirAluno.setText("Excluir");
        jButtonExcluirAluno.setEnabled(false);
        jButtonExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAlunoActionPerformed(evt);
            }
        });

        jTableAluno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAluno);

        jTextFieldPesquisaAluno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldPesquisaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaAlunoActionPerformed(evt);
            }
        });

        jButtonPesquisaAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPesquisaAluno.setText("Pesquisar");
        jButtonPesquisaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaAlunoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Codigo:");

        jTextFieldCodigoAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCodigoAlu.setEnabled(false);
        jTextFieldCodigoAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoAluActionPerformed(evt);
            }
        });

        jTextFieldPaiAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldPaiAlu.setEnabled(false);
        jTextFieldPaiAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaiAluActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Pai:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Telefone:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Celular:");

        try {
            jFormattedTextFieldFoneAlu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFoneAlu.setText("(**) ****-****");
        jFormattedTextFieldFoneAlu.setEnabled(false);
        jFormattedTextFieldFoneAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jFormattedTextFieldFoneAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFoneAluActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Data de Nascimento:");

        try {
            jFormattedTextFieldNascAlu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNascAlu.setText("**/**/****");
        jFormattedTextFieldNascAlu.setToolTipText("");
        jFormattedTextFieldNascAlu.setEnabled(false);
        jFormattedTextFieldNascAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jFormattedTextFieldNascAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNascAluActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCelularAlu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelularAlu.setText("(**) * ****-****");
        jFormattedTextFieldCelularAlu.setEnabled(false);
        jFormattedTextFieldCelularAlu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jFormattedTextFieldCelularAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelularAluActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormProfessorLayout = new javax.swing.GroupLayout(jPanelFormProfessor);
        jPanelFormProfessor.setLayout(jPanelFormProfessorLayout);
        jPanelFormProfessorLayout.setHorizontalGroup(
            jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisaAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaAluno))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeAlu)
                            .addComponent(jTextFieldPaiAlu)))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaeAlu))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldNascAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldFoneAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCelularAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanelFormProfessorLayout.setVerticalGroup(
            jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCodigoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNomeAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMaeAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPaiAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldNascAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextFieldFoneAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jFormattedTextFieldCelularAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFormProfessorLayout.createSequentialGroup()
                        .addComponent(jButtonNovoAlu)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirAluno)))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Alunos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFormProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFormProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );

        setSize(new java.awt.Dimension(687, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeAluActionPerformed

    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

   
    
    private void jButtonSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlunoActionPerformed
        if (jTextFieldNomeAlu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o NOME para continuar");
            jTextFieldNomeAlu.requestFocus();
        }else if (jTextFieldMaeAlu.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Informe o Nome da MÃE do Aluno");
            jTextFieldMaeAlu.requestFocus();
        }else if (jFormattedTextFieldFoneAlu.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Informe a Data de NASCIMENTO para continuar");
            jFormattedTextFieldFoneAlu.requestFocus();
        }else if (jFormattedTextFieldCelularAlu.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Informe o CELULAR para continuar");
            jFormattedTextFieldCelularAlu.requestFocus();
        } else
        if (key == 1) {
           mod.setAlu_nome(jTextFieldNomeAlu.getText());
           mod.setAlu_mae(jTextFieldMaeAlu.getText());
           mod.setAlu_pai(jTextFieldPaiAlu.getText());
           mod.setAlu_nasc(jFormattedTextFieldNascAlu.getText());
           mod.setAlu_tel(jFormattedTextFieldFoneAlu.getText());
           mod.setAlu_cel(jFormattedTextFieldCelularAlu.getText());
           control.Salvar(mod);
           
           jTextFieldNomeAlu.setText("");
           jTextFieldMaeAlu.setText("");
           jTextFieldPaiAlu.setText("");
           jFormattedTextFieldNascAlu.setText("");
           jFormattedTextFieldFoneAlu.setText("");
           jFormattedTextFieldCelularAlu.setText("");
           
           jTextFieldNomeAlu.setEnabled(false);
           jTextFieldMaeAlu.setEnabled(false);
           jTextFieldPaiAlu.setEnabled(false);
           jFormattedTextFieldNascAlu.setEnabled(false);
           jFormattedTextFieldFoneAlu.setEnabled(false);
           jFormattedTextFieldCelularAlu.setEnabled(false);
           
           jButtonSalvarAluno.setEnabled(false);
           jButtonCancelarAluno.setEnabled(false);
           jButtonPesquisaAluno.setEnabled(true);
           jTextFieldPesquisaAluno.setText("");
           jTextFieldPesquisaAluno.setEnabled(true);
           key = 0;
           preencherTablela("select * from aluno order by NOME_ALU;");
       } else
          
       if (key == 2){
           mod.setAlu_cod(Integer.parseInt(jTextFieldCodigoAlu.getText()));
           mod.setAlu_nome(jTextFieldNomeAlu.getText());
           mod.setAlu_mae(jTextFieldMaeAlu.getText());
           mod.setAlu_pai(jTextFieldPaiAlu.getText());
           mod.setAlu_nasc(jFormattedTextFieldNascAlu.getText());
           mod.setAlu_tel(jFormattedTextFieldFoneAlu.getText());
           mod.setAlu_cel(jFormattedTextFieldCelularAlu.getText());
           control.Editar(mod);
           
           jTextFieldCodigoAlu.setText("");
           jTextFieldNomeAlu.setText("");
           jTextFieldMaeAlu.setText("");
           jTextFieldPaiAlu.setText("");
           jFormattedTextFieldNascAlu.setText("");
           jFormattedTextFieldFoneAlu.setText("");
           jFormattedTextFieldCelularAlu.setText("");
           
           jTextFieldNomeAlu.setEnabled(false);
           jTextFieldMaeAlu.setEnabled(false);
           jTextFieldPaiAlu.setEnabled(false);
           jFormattedTextFieldNascAlu.setEnabled(false);
           jFormattedTextFieldFoneAlu.setEnabled(false);
           jFormattedTextFieldCelularAlu.setEnabled(false);
          
           jButtonNovoAlu.setEnabled(true);
           jButtonCancelarAluno.setEnabled(false);
           
           key = 0;
           preencherTablela("select * from aluno order by NOME_ALU;");
       }
       
    }//GEN-LAST:event_jButtonSalvarAlunoActionPerformed

    private void jButtonNovoAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoAluActionPerformed
        key = 1;
        jTextFieldCodigoAlu.setText("");
        jTextFieldNomeAlu.setText("");
        jTextFieldMaeAlu.setText("");
        jTextFieldPaiAlu.setText("");
        jFormattedTextFieldNascAlu.setText("");
        jFormattedTextFieldFoneAlu.setText("");
        jFormattedTextFieldCelularAlu.setText("");
           
        jTextFieldPesquisaAluno.setEnabled(false);
        jTextFieldNomeAlu.setEnabled(true);
        jTextFieldMaeAlu.setEnabled(true);
        jTextFieldPaiAlu.setEnabled(true);
        jFormattedTextFieldNascAlu.setEnabled(true);
        jFormattedTextFieldFoneAlu.setEnabled(true);
        jFormattedTextFieldCelularAlu.setEnabled(true);
        
        jButtonSalvarAluno.setEnabled(true);
        jButtonEditarAluno.setEnabled(false);
        jButtonExcluirAluno.setEnabled(false);
        jButtonPesquisaAluno.setEnabled(false);
        jButtonCancelarAluno.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoAluActionPerformed

    private void jTextFieldMaeAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaeAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaeAluActionPerformed

    private void jButtonPesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaAlunoActionPerformed
        mod.setAlu_pesquisa(jTextFieldPesquisaAluno.getText());
        BeansAluno model = control.buscaBeansAluno(mod);
        jTextFieldNomeAlu.setText(model.getAlu_nome());
        jTextFieldCodigoAlu.setText(String.valueOf(model.getAlu_cod()));
        jTextFieldMaeAlu.setText(model.getAlu_mae());
        jTextFieldPaiAlu.setText(model.getAlu_pai());
        jFormattedTextFieldNascAlu.setText(model.getAlu_nasc());
        jFormattedTextFieldFoneAlu.setText(model.getAlu_tel());
        jFormattedTextFieldCelularAlu.setText(model.getAlu_cel());
        
        preencherTablela("select*from aluno where NOME_ALU like'%"+mod.getAlu_pesquisa()+"%'");
       
    }//GEN-LAST:event_jButtonPesquisaAlunoActionPerformed

    private void jButtonCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAlunoActionPerformed
        jTextFieldCodigoAlu.setText("");
        jTextFieldNomeAlu.setText("");
        jTextFieldMaeAlu.setText("");
        jTextFieldPaiAlu.setText("");
        jFormattedTextFieldNascAlu.setText("");
        jFormattedTextFieldFoneAlu.setText("");
        jFormattedTextFieldCelularAlu.setText("");
        
        jTextFieldPesquisaAluno.setEnabled(true);
        jTextFieldNomeAlu.setEnabled(false);
        jTextFieldMaeAlu.setEnabled(false);
        jTextFieldPaiAlu.setEnabled(false);
        jFormattedTextFieldNascAlu.setEnabled(false);
        jFormattedTextFieldCelularAlu.setEnabled(false);
        jFormattedTextFieldFoneAlu.setEnabled(false);
        
        jButtonPesquisaAluno.setEnabled(true);
        jButtonSalvarAluno.setEnabled(false);
        jButtonCancelarAluno.setEnabled(false);
        jButtonNovoAlu.setEnabled(true);
        jButtonEditarAluno.setEnabled(false);
        jButtonExcluirAluno.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarAlunoActionPerformed

    private void jButtonEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAlunoActionPerformed
        key = 2;
        jTextFieldNomeAlu.setEnabled(true);
        jTextFieldMaeAlu.setEnabled(true);
        jTextFieldPaiAlu.setEnabled(true);
        jFormattedTextFieldNascAlu.setEnabled(true);
        jFormattedTextFieldCelularAlu.setEnabled(true);           
        jFormattedTextFieldFoneAlu.setEnabled(true);
        
        jButtonSalvarAluno.setEnabled(true);
        jButtonCancelarAluno.setEnabled(true);
        jButtonEditarAluno.setEnabled(false);
        jButtonNovoAlu.setEnabled(false);
        jButtonExcluirAluno.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarAlunoActionPerformed

    private void jTextFieldCodigoAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoAluActionPerformed

    private void jTextFieldPaiAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaiAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaiAluActionPerformed

    private void jFormattedTextFieldFoneAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFoneAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFoneAluActionPerformed

    private void jButtonExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAlunoActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setAlu_cod(Integer.parseInt(jTextFieldCodigoAlu.getText()));
            control.Excluir(mod);
            jTextFieldNomeAlu.setText("");
            jTextFieldMaeAlu.setText("");
            jTextFieldPaiAlu.setText("");
            jFormattedTextFieldNascAlu.setText("");
            jFormattedTextFieldFoneAlu.setText("");
            jFormattedTextFieldCelularAlu.setText("");
            jTextFieldCodigoAlu.setText("");
            jTextFieldPesquisaAluno.setText("");
            
            jTextFieldNomeAlu.setEnabled(false);
            jTextFieldMaeAlu.setEnabled(false);
            jTextFieldPaiAlu.setEnabled(false);
            jFormattedTextFieldNascAlu.setEnabled(false);
            jFormattedTextFieldCelularAlu.setEnabled(false);
            jFormattedTextFieldFoneAlu.setEnabled(false);
            
            jButtonSalvarAluno.setEnabled(false);
            jButtonEditarAluno.setEnabled(false);
            jButtonExcluirAluno.setEnabled(false);
            jButtonCancelarAluno.setEnabled(false);
            preencherTablela("select * from aluno order by NOME_ALU;");
        }
    }//GEN-LAST:event_jButtonExcluirAlunoActionPerformed

    private void jTableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunoMouseClicked
        String nome_aluno = ""+jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 1);
        conex.conecxao();
        conex.executaSql("select * from aluno where NOME_ALU = '" + nome_aluno + "';");
        try {
            conex.rs.first();
            
            jTextFieldCodigoAlu.setText(String.valueOf(conex.rs.getString("COD_ALU")));
            jTextFieldNomeAlu.setText(conex.rs.getString("NOME_ALU"));
            jTextFieldMaeAlu.setText(conex.rs.getString("MAE_ALU"));
            jTextFieldPaiAlu.setText(conex.rs.getString("PAI_ALU"));
            ConvData(conex.rs.getString("NASC_ALU"));
            jFormattedTextFieldNascAlu.setText(data_banco);
            jFormattedTextFieldFoneAlu.setText(conex.rs.getString("FONE_ALU"));
            jFormattedTextFieldCelularAlu.setText(conex.rs.getString("CEL__ALU"));
            
            jButtonEditarAluno.setEnabled(true);
            jButtonExcluirAluno.setEnabled(true);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao Selecionar os Dados!" + ex);
        }
        
        conex.desconectar();
    }//GEN-LAST:event_jTableAlunoMouseClicked

    private void jTextFieldPesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaAlunoActionPerformed

    private void jFormattedTextFieldNascAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNascAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNascAluActionPerformed

    private void jFormattedTextFieldCelularAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelularAluActionPerformed

   public void preencherTablela(String Sql) {
       ArrayList dados = new ArrayList();
       String [] colunas = new String [] {"ID","Nome Aluno","Nome Mãe","Nome Pai","Data de Nasc","Telefone","Celular"};
       conex.conecxao();
       
       conex.executaSql(Sql);
       
       try{
           conex.rs.first();
           do {
               ConvData(conex.rs.getString("NASC_ALU"));
               dados.add(new Object[]{conex.rs.getInt("COD_ALU"),conex.rs.getString("NOME_ALU"),conex.rs.getString("MAE_ALU"),conex.rs.getString("PAI_ALU"),data_banco,conex.rs.getString("FONE_ALU"),conex.rs.getString("CEL__ALU")});  
           }while(conex.rs.next());
           
       }catch(SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Nenhum resultado encontrado na tabela.");
       }
       ModeloTabela modelo = new ModeloTabela(dados, colunas);
       
       jTableAluno.setModel(modelo);
       jTableAluno.getColumnModel().getColumn(0).setPreferredWidth(30);
       jTableAluno.getColumnModel().getColumn(0).setResizable(false);
       jTableAluno.getColumnModel().getColumn(1).setPreferredWidth(140);
       jTableAluno.getColumnModel().getColumn(1).setResizable(false);
       jTableAluno.getColumnModel().getColumn(2).setPreferredWidth(140);
       jTableAluno.getColumnModel().getColumn(2).setResizable(false);
       jTableAluno.getColumnModel().getColumn(3).setPreferredWidth(140);
       jTableAluno.getColumnModel().getColumn(3).setResizable(false);
       jTableAluno.getColumnModel().getColumn(4).setPreferredWidth(100);
       jTableAluno.getColumnModel().getColumn(4).setResizable(false);
       jTableAluno.getColumnModel().getColumn(5).setPreferredWidth(100);
       jTableAluno.getColumnModel().getColumn(5).setResizable(false);
       jTableAluno.getColumnModel().getColumn(6).setPreferredWidth(100);
       jTableAluno.getColumnModel().getColumn(6).setResizable(false);
       jTableAluno.getTableHeader().setReorderingAllowed(false);
       jTableAluno.setAutoResizeMode(jTableAluno.AUTO_RESIZE_OFF);
       jTableAluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
       conex.desconectar();
   } 
   
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new FormAluno().setVisible(true);
            }
        });
    }
    
    public void ConvData (String data) {

        try {
            data_inicial = new SimpleDateFormat("yyyy-MM-dd").parse(data);
            data_banco = new SimpleDateFormat("dd/MM/yyyy").format(data_inicial);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro"+ex);
        }
 
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarAluno;
    private javax.swing.JButton jButtonEditarAluno;
    private javax.swing.JButton jButtonExcluirAluno;
    private javax.swing.JButton jButtonNovoAlu;
    private javax.swing.JButton jButtonPesquisaAluno;
    private javax.swing.JButton jButtonSalvarAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularAlu;
    private javax.swing.JFormattedTextField jFormattedTextFieldFoneAlu;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascAlu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelFormProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTextField jTextFieldCodigoAlu;
    private javax.swing.JTextField jTextFieldMaeAlu;
    private javax.swing.JTextField jTextFieldNomeAlu;
    private javax.swing.JTextField jTextFieldPaiAlu;
    private javax.swing.JTextField jTextFieldPesquisaAluno;
    // End of variables declaration//GEN-END:variables
}
